

class IntelligentTerminalATOffline < Formula
  include Language::Python::Virtualenv

  desc "AI-assisted terminal with natural-language commands, suggestions, and error explainers (offline vendored)"
  homepage "https://intelligent-terminal.com"
  url "https://github.com/1DigitalPartner/intelligent-terminal/releases/download/v0.1.1/intelligent_terminal-0.1.1.tar.gz"
  sha256 "b6c92d29579e90fe891a496ff80394290dea6d2005cb120593a3930e6afb4734"
  license "MIT"

  depends_on "python@3.11"

  # Install using vendored resources (generated by `brew update-python-resources`)
  def install
    virtualenv_install_with_resources
  end

  test do
    output = shell_output("#{bin}/intelligent-terminal -h 2>&1 || true")
    assert_match "AI Terminal", output
  end
end
